### ISSUE TITLE
Further Discussion

### ISSUE THREAD

**Issue by andrerfneves** [c-h-/universal-native-boilerplate#1]
Hey @c-h- just re-starting the chat from macOS repo. I'm gonna try the package out in a couple minutes and will be able to give you more feedback. Looks pretty awesome though. Anything in specific I should look out for while building?

How are you testing/running the react-native-windows apps on mac btw?

**Comment by c-h-** [comment]
Hey @andrerfneves sounds good - I believe things should be working fine.

Just remember to `gulp enable <platform>` for each one you want. The "enable" function simply [gets dependencies](https://github.com/c-h-/universal-native-boilerplate/blob/master/boilerplate/recipes.json) and installs them.

The macOS version is the least mature; I'm hoping to make progress on there and contribute to the react-native-macos project to make it more robust.

Besides that there really isn't a lot to know if you're familiar with React/React Native.

My primary computer is a Surface Book so I just run Windows on there - I use a MacBook Pro for iOS/macOS.

Thank you for your interest!!

**Comment by c-h-** [comment]
Closing unless there's more to discuss here
